"""
Responsible for saving and retrieving conversation episodes using ChromaDB.
"""

import chromadb
from datetime import datetime

# Initilize persistent ChromaDB client
_client = chromadb.PersistentClient(path='chroma_db')
_collection = _client.get_or_create_collection(name='episodic_memory')

def save_episode(
    user_message: str,
    agent_response: str,
    embedding: list[float]
) -> None:
    """
    Saves a conversation episode to the vector database

    Args:
        user_message: The message sent by the user.
        agent_response: The response generated by the agent.
        embedding: The vector embedding of the user message.
    """
    episode_id = datetime.now().strftime("%Y%m%d%H%M%S%f")
    document = f"User: {user_message}\nAgent: {agent_response}"

    _collection.add(
        ids=[episode_id],
        documents=[document],
        embeddings=[embedding],
        metadatas=[{"timestamp": datetime.now().isoformat()}]
    )
        
def retrieve_similar_episodes(
    embedding: list[float],
    top_k: int = 3
) -> list[str]:
    """
    Retrieves the most similar past episodes given an embedding.
    
    Args:
        embedding: The vector embedding of the current user message.
        top_k: Number of similar episodes to retrieve.
    
    Returns:
        A list of past episode strings ordered by similarity.
    """
    results = _collection.query(
        query_embeddings=[embedding],
        n_results=top_k
    )
    
    documents = results.get("documents", [[]])[0] # type: ignore
    return documents
