"""
Responsible for saving and retrieving conversation episodes using ChromaDB.
"""

import chromadb
from datetime import datetime


class MemoryStore:
    """
    Handles persistent storage and retrieval of conversation episodes using ChromaDB.

    Attributes:
        _client: Private PersistentClient instance connected to the ChromaDB database.
        _collection: Private ChromaDB collection storing episodic memory documents.
    """

    def __init__(self, path: str = "chroma_db"):
        """
        Initializes the MemoryStore by creating a ChromaDB client and collection.

        Args:
            path: Path to the ChromaDB persistent storage directory. Defaults to 'chroma_db'.
        """
        self._client = chromadb.PersistentClient(path=path)
        self._collection = self._client.get_or_create_collection(name="episodic_memory")

    def save_episode(
        self, user_message: str, agent_response: str, embedding: list[float]
    ) -> None:
        """
        Saves a conversation episode to the vector database.

        Args:
            user_message: The message sent by the user.
            agent_response: The response generated by the agent.
            embedding: The vector embedding of the user message.
        """
        episode_id = datetime.now().strftime("%Y%m%d%H%M%S%f")
        document = f"User: {user_message}\nAgent: {agent_response}"

        self._collection.add(
            ids=[episode_id],
            documents=[document],
            embeddings=[embedding],
            metadatas=[{"timestamp": datetime.now().isoformat()}],
        )

    def retrieve_similar_episodes(
        self, embedding: list[float], top_k: int = 3
    ) -> list[str]:
        """
        Retrieves the most similar past episodes given an embedding.

        Args:
            embedding: The vector embedding of the current user message.
            top_k: Number of similar episodes to retrieve.

        Returns:
            A list of past episode strings ordered by similarity.
        """
        results = self._collection.query(query_embeddings=[embedding], n_results=top_k)

        documents = results.get("documents", [[]])[0] # type: ignore
        return documents
